### ISSUE TITLE
Old codebase

### ISSUE THREAD

**Issue by samoht9277** [BlueAndi/niu-cloud-connector#6]
Running this on a MacBook Air M2, 2022.

Only by changing my credentials, I get multiple error right off the bat. I assume these errors are due to the differences between NodeJS versions.

My NodeJS version is `v21.5.0` and npm is at `10.2.4`

**Comment by BlueAndi** [comment]
@samoht9277 I updated for NodeJS v18.13.0 on my latest Debian. Can you verify via the CLI please? https://github.com/BlueAndi/niu-cloud-cli/tree/development

With the upgrade for ES6 Modules it should work for you as well.

**Comment by BlueAndi** [comment]
Verified by someone else.

**Comment by samoht9277** [comment]
Awesome! Thanks @BlueAndi!
